-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 17:51:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vivero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vivero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vivero` DEFAULT CHARACTER SET utf8 ;
USE `Vivero` ;

-- -----------------------------------------------------
-- Table `Vivero`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`VIVERO` (
  `coordenadas` FLOAT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`coordenadas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`ZONA` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`PRODUCTO` (
  `codigo_prod` VARCHAR(45) NOT NULL,
  `stock` INT NULL,
  `precio` DECIMAL NOT NULL,
  PRIMARY KEY (`codigo_prod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`EMPLEADO` (
  `dni` VARCHAR(9) NOT NULL,
  `sueldo` DECIMAL NOT NULL,
  `css` VARCHAR(11) NOT NULL,
  `antiguedad` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`CLIENTE` (
  `dni` VARCHAR(9) NOT NULL,
  `bonificacion` DECIMAL NULL,
  `total_mensual` DECIMAL NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`VIVERO_ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`VIVERO_ZONA` (
  `VIVERO_coordenadas` FLOAT NOT NULL,
  `ZONA_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VIVERO_coordenadas`, `ZONA_nombre`),
  INDEX `fk_VIVERO_has_ZONA_ZONA1_idx` (`ZONA_nombre` ASC) VISIBLE,
  INDEX `fk_VIVERO_has_ZONA_VIVERO_idx` (`VIVERO_coordenadas` ASC) VISIBLE,
  CONSTRAINT `fk_VIVERO_ZONA_VIVERO`
    FOREIGN KEY (`VIVERO_coordenadas`)
    REFERENCES `Vivero`.`VIVERO` (`coordenadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIVERO_ZONA_ZONA1`
    FOREIGN KEY (`ZONA_nombre`)
    REFERENCES `Vivero`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`ZONA_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`ZONA_EMPLEADO` (
  `ZONA_nombre` VARCHAR(45) NOT NULL,
  `EMPLEADO_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ZONA_nombre`, `EMPLEADO_dni`),
  INDEX `fk_ZONA_has_EMPLEADO_EMPLEADO1_idx` (`EMPLEADO_dni` ASC) VISIBLE,
  INDEX `fk_ZONA_has_EMPLEADO_ZONA1_idx` (`ZONA_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_ZONA_EMPLEADO_ZONA1`
    FOREIGN KEY (`ZONA_nombre`)
    REFERENCES `Vivero`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONA_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_dni`)
    REFERENCES `Vivero`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`PRODUCTO_ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`PRODUCTO_ZONA` (
  `PRODUCTO_codigo_prod` VARCHAR(45) NOT NULL,
  `ZONA_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCTO_codigo_prod`, `ZONA_nombre`),
  INDEX `fk_PRODUCTO_has_ZONA_ZONA1_idx` (`ZONA_nombre` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_ZONA_PRODUCTO1_idx` (`PRODUCTO_codigo_prod` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_ZONA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo_prod`)
    REFERENCES `Vivero`.`PRODUCTO` (`codigo_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_ZONA_ZONA1`
    FOREIGN KEY (`ZONA_nombre`)
    REFERENCES `Vivero`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vivero`.`PRODUCTO_CLIENTE_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vivero`.`PRODUCTO_CLIENTE_EMPLEADO` (
  `PRODUCTO_codigo_prod` VARCHAR(45) NOT NULL,
  `CLIENTE_dni` VARCHAR(9) NOT NULL,
  `EMPLEADO_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`PRODUCTO_codigo_prod`, `CLIENTE_dni`, `EMPLEADO_dni`),
  INDEX `fk_PRODUCTO_CLIENTE_EMPLEADO_CLIENTE1_idx` (`CLIENTE_dni` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_CLIENTE_EMPLEADO_EMPLEADO1_idx` (`EMPLEADO_dni` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CLIENTE_EMPLEADO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo_prod`)
    REFERENCES `Vivero`.`PRODUCTO` (`codigo_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_CLIENTE_EMPLEADO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_dni`)
    REFERENCES `Vivero`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_CLIENTE_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_dni`)
    REFERENCES `Vivero`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `Vivero`.`VIVERO`
-- -----------------------------------------------------
START TRANSACTION;
USE `Vivero`;
INSERT INTO `Vivero`.`VIVERO` (`coordenadas`, `localidad`) VALUES (28°28\'55.7\"N 16°17\'24.5\"W, 'La Cuesta');
INSERT INTO `Vivero`.`VIVERO` (`coordenadas`, `localidad`) VALUES (28°33\'07.7\"N 16°21\'09.5\"W, 'La Laguna');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Vivero`.`ZONA`
-- -----------------------------------------------------
START TRANSACTION;
USE `Vivero`;
INSERT INTO `Vivero`.`ZONA` (`nombre`) VALUES ('Zona exterior');
INSERT INTO `Vivero`.`ZONA` (`nombre`) VALUES ('Cajas');
INSERT INTO `Vivero`.`ZONA` (`nombre`) VALUES ('Almacen');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Vivero`.`PRODUCTO`
-- -----------------------------------------------------
START TRANSACTION;
USE `Vivero`;
INSERT INTO `Vivero`.`PRODUCTO` (`codigo_prod`, `stock`, `precio`) VALUES ('9654158633604619', 6, 55);
INSERT INTO `Vivero`.`PRODUCTO` (`codigo_prod`, `stock`, `precio`) VALUES ('0636937512193258', 10, 23);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Vivero`.`EMPLEADO`
-- -----------------------------------------------------
START TRANSACTION;
USE `Vivero`;
INSERT INTO `Vivero`.`EMPLEADO` (`dni`, `sueldo`, `css`, `antiguedad`) VALUES ('43841764S', 800, '26801685401', '2 años');
INSERT INTO `Vivero`.`EMPLEADO` (`dni`, `sueldo`, `css`, `antiguedad`) VALUES ('42356732J', 1280, '86319609215', '5 años');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Vivero`.`CLIENTE`
-- -----------------------------------------------------
START TRANSACTION;
USE `Vivero`;
INSERT INTO `Vivero`.`CLIENTE` (`dni`, `bonificacion`, `total_mensual`) VALUES ('53691594F', 15,05, 331);
INSERT INTO `Vivero`.`CLIENTE` (`dni`, `bonificacion`, `total_mensual`) VALUES ('41599623M', 12,25, 245);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
